# Generated by Django 4.0.6 on 2022-08-05 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('piso', models.IntegerField()),
                ('capacidad', models.IntegerField()),
                ('descripcion', models.CharField(max_length=150)),
                ('ocupada', models.BooleanField()),
                ('precio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('fechaApertura', models.DateField(max_length=40)),
                ('abierto', models.BooleanField()),
                ('estrellas', models.IntegerField()),
                ('ciudad', models.CharField(max_length=50)),
                ('pais', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('fechaDesde', models.DateField(max_length=40)),
                ('fechaHasta', models.DateField(max_length=30)),
                ('cantPersonas', models.IntegerField()),
                ('comentarios', models.CharField(max_length=200)),
                ('metodoPago', models.CharField(max_length=200)),
                ('habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppProyFinal.habitacion')),
            ],
        ),
        migrations.AddField(
            model_name='habitacion',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppProyFinal.hotel'),
        ),
    ]
